buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

plugins {
    id 'com.android.application' version '8.12.3' apply false  // From agp in catalog
    id 'org.jetbrains.kotlin.android' version '2.2.21' apply false  // From kotlin
    id 'org.jetbrains.kotlin.plugin.compose' version '2.2.21' apply false  // From compose-compiler
    id 'io.github.takahirom.roborazzi' version '1.51.0' apply false  // From roborazzi
}