plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'org.opencv'
    compileSdk 36
    ndkVersion "29.0.14206865"

    defaultConfig {
        compileSdk
        minSdk 24
        targetSdk 36

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin {
        jvmToolchain(21)
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'

        }
    }
    buildFeatures{
        aidl true
        buildConfig true
    }
    sourceSets {
        main {
            jni.srcDirs += ['src/sdk/native/jni/include']
            jniLibs.srcDirs += ['src/sdk/native/libs', 'build/intermediates/cxx/debug/obj']
            java.srcDirs += ['src/sdk/java/src']
            res.srcDirs += ['src/sdk/java/res']
        }
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true  // Force pack .so dans AAR
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
}